### ISSUE TITLE
Distribution of work

### ISSUE THREAD

**Issue by abenaTenkorang** [abenaTenkorang/react_group_project#25]
This project has 2 assignees

Group
[create APP and basic setup](https://github.com/users/abenaTenkorang/projects/2?pane=issue&itemId=25211827)
[website header](https://github.com/users/abenaTenkorang/projects/2?pane=issue&itemId=25211828)
[empty profile](https://github.com/users/abenaTenkorang/projects/2?pane=issue&itemId=25211829)
Abi
[rocket display](https://github.com/users/abenaTenkorang/projects/2?pane=issue&itemId=25211830)
[fetch rocket data](https://github.com/users/abenaTenkorang/projects/2?pane=issue&itemId=25211833)
[display rocket](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211835)
[implement rocket booking](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=252118385)
[implement rocket booking cancellation](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211842)
[switch badges](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211845)
[display reversed rocket](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211848)

Esther
[mission display](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211831)
[fetch mission data](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211834)
[display mission](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211837)
[implement mission joining](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211840)
[implement leaving mission](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211842)
[switch mission badges](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211846)
[display joined mission](https://github.com/users/abenaTenkorang/projects/2/views/1?pane=issue&itemId=25211849)

Project link
[Github project link](https://github.com/users/abenaTenkorang/projects/2)

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️
- Tasks distributed equally ✔️

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
